
name: cron

on:
  schedule:
    - cron: "1 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'
      
      - name: Install
        run: |
          npm ci
      
      - name: Collect
        run: |
          npm start
      
      - name: Add
        run: |
          git config --global user.email "davidtronfivethousand@gmail.com"
          git config --global user.name "David Wells Bot"
          git status
          git add .
          git commit -m ":package: Update Downloads" || exit 0
      
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
